import { Card, BottomNavigation, Stack, Typography, Slider, CircularProgress, Paper } from '@mui/material';
import { Stepper, Step, StepLabel, StepContent, StepButton } from '@mui/material';
import CommentIcon from '@mui/icons-material/InsertCommentOutlined';
import FullscreenIcon from '@mui/icons-material/FullscreenRounded';
import VolumeOffIcon from '@mui/icons-material/VolumeOffRounded';
import VolumeOnIcon from '@mui/icons-material/VolumeUpRounded';
import ForwardIcon from '@mui/icons-material/Forward10Rounded';
import PerformanceIcon from '@mui/icons-material/SpeedRounded';
import RewindIcon from '@mui/icons-material/Replay10Rounded';
import React, { useState, useEffect , useRef } from 'react';
import PlayIcon from '@mui/icons-material/PlayArrowRounded';
import FlagIcon from '@mui/icons-material/OutlinedFlag';
import PauseIcon from '@mui/icons-material/Pause';
import ArrowIcon from '@mui/icons-material/West';
import { GetServerSideProps } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';


export default function Watch( media: any ) {
	const [showControls, setShowControls] = useState(true);
  const [activeStep, setActiveStep] = React.useState(2);
	const [fullscreen, setFullscreen] = useState(false);
  const [progress, setProgress] = useState('00:00');
	const [loaded, setLoaded] = useState(false);
  const [duration, setDuration] = useState(0);
  const [volume, setVolume] = useState(100);
  const [mute, setMute] = useState(false);
  const [play, setPlay] = useState(true);

  const playerRef = useRef<HTMLVideoElement>(null);
  const timerRef = useRef<number>();
  const router = useRouter();

  const steps = [ '0.5x', '0.75x', '1x (Normal)', '1.25x', '1.5x' ];

	const handlePlay = () => {
		setPlay(true);
		playerRef?.current?.play();
	};

	const handlePause = () => {
		setPlay(false);
		playerRef?.current?.pause();
	};

  const handleFullscreen = () => {
    const doc = document.documentElement;

    if (!fullscreen && doc.requestFullscreen) {
      doc.requestFullscreen();
    } else if (fullscreen && document.exitFullscreen) {
      document.exitFullscreen();
    }

    setFullscreen(!fullscreen);
  };

  const handleForward = () => {
    if (playerRef.current) {
      playerRef.current.currentTime += 10;
    }
  };

  const handleRewind = () => {
    if (playerRef.current) {
      playerRef.current.currentTime -= 10;
    }
  };

  const handleStep = (step: number) => () => {
    setActiveStep(step);
  };

	useEffect(() => {
		const resetTimer = () => {
			if (timerRef.current) {
				clearTimeout(timerRef.current);
			}
			timerRef.current = window.setTimeout(() => {
				setShowControls(false);
			}, 3000);
		};

		const handleMouseMove = () => {
			setShowControls(true);
			resetTimer();
		};

		window.addEventListener('mousemove', handleMouseMove);
		resetTimer();

		return () => {
			window.removeEventListener('mousemove', handleMouseMove);
			clearTimeout(timerRef.current);
		};
	}, []);

	useEffect(() => {
		if (media.media) {
			setLoaded(true);
		}
		setInterval(() => {
			if (playerRef.current) {
				const duration = playerRef.current.duration;
				const currentTime = playerRef.current.currentTime;
				const progress = (currentTime / duration) * 100;
				setDuration(progress);
			
				const hours = Math.floor(progress / 3600);
				const minutes = Math.floor((progress % 3600) / 60);
				const seconds = Math.floor(progress % 60);
			
				const timeFormat = `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
				if(hours <= 0) {
					setProgress(timeFormat.slice(3));
				} else {
					setProgress(timeFormat);
				}
			}
		}, 500);
	}, []);

  return (
		<>
		<Head>
			<title>Nyetflix</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		{loaded ? (
    <Card
      style={{
				backgroundColor: '#000',
        position: 'absolute',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
        width: '100%',
      }}
    >
      <ArrowIcon
        onClick={() => {
					if (fullscreen) {
						handleFullscreen();
          }
          router.back();
        }}
        sx={{
					display: showControls ? 'flex' : 'none',
          position: 'absolute',
          fontWeight: 'bold',
          cursor: 'pointer',
          fontSize: '55px',
          color: '#fff',
          left: '25px',
          zIndex: 100,
          top: '25px',
        }}
      />
      <FlagIcon
        sx={{
					display: showControls ? 'flex' : 'none',
          transform: 'scaleX(1.3)',
          position: 'absolute',
          cursor: 'pointer',
          fontSize: '55px',
          color: '#fff',
          right: '50px',
          zIndex: 100,
          top: '25px',
        }}
      />
      <video
        style={{
          objectFit: 'cover',
          height: '100%',
          width: '100%',
        }}
        src={`/data/movies/trailers/${media.id}.mp4` }
        controls={false}
        autoPlay={true}
        muted={mute}
        ref={playerRef}
        loop={false}
      />       
      	<BottomNavigation
					sx={{
						backgroundColor: 'transparent',
						position: 'absolute',
						width: '100%',
						height: '15.5%',
						bottom: 0,
						display: showControls ? 'flex' : 'none',
					}}
				>
					<Stack direction="column" spacing={0} sx={{
							width: '100%',
							display: 'flex',
							justifyContent: 'left',
							alignItems: 'center',
							height: '100%',
							margin: '0 .7vw',
							backgroundColor: 'transparent',
						}}
					>
						<Stack direction="row" spacing={1} sx={{
								width: '100%',
								display: 'flex',
								justifyContent: 'left',
								alignItems: 'center',
							}}
						>
							<div
								style={{
									width: '96%',
									padding: '0.5vw',
									display: 'flex',
									justifyContent: 'left',
									alignItems: 'center',
								}}
							>
								<Slider
                	min={0}
									max={100}
                  value={duration}
									onChange={(e: any) => {
										if (playerRef.current) {
											const duration = playerRef.current.duration;
											const value = e.target.value;
											playerRef.current.currentTime = (value * duration) / 100;
										}
									}}
									sx={{
										width: '100%',
										height: '0.25vw',
										borderRadius: '0',
										padding: '0',
										color: 'red',
										'&:hover': {
											height: '0.4vw',
										},
										'&:hover .MuiSlider-rail': {
											height: '0.4vw',
										},
										'&:hover .MuiSlider-thumb': {
											'&:clicked': {
												boxShadow: '0px 0px 0px 8px rgba(255,255,255,0.16)',
											},
										},
										'& .MuiSlider-thumb': {
											width: '.8vw',
											height: '.8vw',
										},
										'& .MuiSlider-rail': {
											height: '0.25vw',
											backgroundColor: 'rgba(255,255,255,1)',
										},
									}}
								/>
							</div>
							<Typography
								sx={{
									fontSize: '.95vw',
									fontWeight: '500',
									letterSpacing: '0.05vw',
									color: 'rgba(255,255,255,1)',
								}}
							>
								{progress}
							</Typography>
						</Stack>
						<Stack direction="row" spacing={2} sx={{
								justifyContent: 'left',
								position: 'absolute',
								alignItems: 'center',
								display: 'flex',
								bottom: '1.5vw',
								left: '.7vw',
								zIndex: 2,
							}}
						>
						{!play ? (
							<PlayIcon
								onClick={() => handlePlay()}
								sx={{
									transition: 'all 0.1s ease-in-out',
									transform: 'scale(1.4)',
									cursor: 'pointer',
									fontSize: '3vw',
									color: '#fff',
									'&:hover': {
										transform: 'scale(1.8)',
									},
								}}
							/>
						) : (
							<PauseIcon
								onClick={() => handlePause()}
								sx={{
									transition: 'all 0.1s ease-in-out',
									cursor: 'pointer',
									fontSize: '3vw',
									color: '#fff',
									'&:hover': {
										transform: 'scale(1.4)',
									},
								}}
							/>
						)}
							<RewindIcon 
								onClick={() => handleRewind()}
								sx={{
									transition: 'all 0.1s ease-in-out',
									cursor: 'pointer',
									fontSize: '3vw',
									color: '#fff',
									'&:hover': {
										transform: 'scale(1.4)',
									},
								}}
							/>
							<ForwardIcon
								onClick={() => handleForward()}
								sx={{
									transition: 'all 0.1s ease-in-out',
									cursor: 'pointer',
									fontSize: '3vw',
									color: '#fff',
									'&:hover': {
										transform: 'scale(1.4)',
									},
								}}
							/>
              <Stack direction="column" spacing={0} sx={{
                  justifyContent: 'center',
                  alignItems: 'center',
                  display: 'flex',
                  '&:hover .volume': {
                    display: 'flex',
                  },
                  '&:hover svg': {
                    transform: 'scale(1.4)',
                  },
                }}
              >
                <Paper
                  className='volume'
                  sx={{ 
                    backgroundColor: '#202020',
                    borderRadius: '.1vw',
                    width: '2vw',
                    height: '10vw',
                    bottom: '3.5vw',
                    position: 'absolute',
                    display: 'none',
                    justifyContent: 'center',
                    alignItems: 'center',
                    zIndex: 2,
                }}>
                  <Slider
                      min={0}
                      max={100}
                      orientation="vertical"
                      valueLabelDisplay="off"
                      className='volume-slider'
                      value={mute ? 0 : volume}
                      sx={{
                        color: 'red',
                        width: '60%',
                        borderRadius: '0',
                        height: '80%',
                        padding: '0',
                        '& input[type="range"]': {
                          WebkitAppearance: 'slider-vertical',
                          },
                        '& .MuiSlider-thumb': {
                          width: '1.1vw',
                          border: 'none',
                          boxShadow: 'none',
                          },
                        '& .MuiSlider-rail': {
                          backgroundColor: 'rgba(255,255,255,1)',
                        },
                      }}
                      onChange={(e: any) => {
                        if (playerRef.current) {
                          const value = e.target.value;
                          playerRef.current.volume = value / 100;
                          setVolume(value);
                        }
                      }}
                  />
              </Paper>
                {!mute && volume != 0 ? (
                  <VolumeOnIcon
                    onClick={() => {
                      setMute(!mute)
                    }}
                      sx={{
                        transition: 'all 0.1s ease-in-out',
                        color: '#fff',
                        cursor: 'pointer',
                        fontSize: '3vw',
                        '&:hover': {
                          transform: 'scale(1.4)',
                        },
                        '&:hover .volume-slider': {
                          display: 'block',
                        },
                      }}
                  />
                ) : (
                  <VolumeOffIcon
                    onClick={() => {
                      setMute(!mute)
                    }}
                    sx={{
                      transition: 'all 0.1s ease-in-out',
                      cursor: 'pointer',
                      fontSize: '3vw',
                      color: '#fff',
                      '&:hover': {
                        transform: 'scale(1.4)',
                      },
                    }}
                  />
                )}
              </Stack>
						</Stack>
						<Stack direction="row" spacing={2} sx={{
								justifyContent: 'center',
								alignItems: 'center',
								display: 'flex',
								height: '100%',
								width: '100%',
							}}
						>
							<Typography sx={{
								fontFamily: 'Netflix Sans,Helvetica Neue,Segoe UI,Roboto,Ubuntu,sans-serif',
								fontWeight: '500',
								fontSize: '1vw',
								color: '#fff',
								}}
							>
								{media.media[0].name}
							</Typography>
						</Stack>
						<Stack direction="row" spacing={4} sx={{
								justifyContent: 'right',
								position: 'absolute',
								marginLeft: 'auto',
								display: 'flex',
								bottom: '1.5vw',
								right: '.7vw',
								zIndex: 100,
							}}
						>
							<CommentIcon
								sx={{
									transition: 'all 0.1s ease-in-out',
									cursor: 'pointer',
									fontSize: '3vw',
									color: '#fff',
									'&:hover': {
										transform: 'scale(1.4)',
									},
								}}
							/>
              <Stack direction="column" spacing={0} sx={{
                  justifyContent: 'center',
                  alignItems: 'center',
                  display: 'flex',
                  '&:hover .quality': {
                    display: 'flex',
                  },
                  '&:hover svg': {
                    transform: 'scale(1.4)',
                  },
                }}
              >
                <Paper
                  className='quality'
                  sx={{
                    backgroundColor: '#202020',
                    width: '43vw',
                    borderRadius: '0.25vw',
                    height: '10vw',
                    bottom: '3.5vw',
                    right: '-.68vw',
                    position: 'absolute',
                    display: 'none',
                    justifyContent: 'center',
                    alignItems: 'center',
                    zIndex: 2,
                }}>
                  <Stack direction="column" spacing={0} sx={{
                      justifyContent: 'center',
                      alignItems: 'center',
                      display: 'flex',
                      width: '100%',
                      height: '100%',
                    }}
                  >
                    <Typography sx={{
                        justifyContent: 'left',
                        alignItems: 'left',
                        textAlign: 'left',
                        fontSize: '28px',
                        fontWeight: '400',
                        display: 'flex',
                        padding: '1vw 2vw',
                        color: '#fff',
                        width: '100%',
                      }}
                    >
                      Playback Speed
                    </Typography>
                    <Stepper activeStep={activeStep}
                      alternativeLabel nonLinear
                      sx={{
                        backgroundColor: 'transparent',
                        width: '100%',
                        height: '100%',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        '& .MuiStep-root': {
                          width: '100%',
                        },
                        // other steps
                        '& .MuiStepIcon-root': {
                          backgroundColor: '#fff',
                          borderRadius: '50%',
                          color: '#fff',
                          width: '.8vw',
                          height: '.8vw',
                          margin: '.2vw',
                          cursor: 'pointer',
                        },
                        // active
                        '& .MuiStepIcon-root.Mui-active': {
                          width: '1.7vw',
                          height: '1.7vw',
                          margin: '-.27vw',
                          color: '#fff',
                          padding: '0 5px',
                          backgroundColor: '#202020',
                          border: '2px solid rgba(255,255,255,.5)',
                          zIndex: 2,
                        },
                        // line
                        '& .MuiStepConnector-line': {
                        },
                        // text color
                        '& .MuiStepLabel-label': {
                          color: '#fff',
                          fontWeight: '400',
                          fontSize: '1.3vw',
                        },
                        '& .MuiStepLabel-label.Mui-active': {
                          color: '#fff',
                          fontWeight: '700',
                          fontSize: '1.3vw',
                        },
                      }}
                    >
                    {steps.map((label, index) => (
                      <Step key={label}>
                        <StepButton disableRipple
                          onClick={() => {
                            setActiveStep(index)
                            if (playerRef.current) {
                              switch (index) {
                                case 0:
                                  playerRef.current.playbackRate = .5
                                  break
                                case 1:
                                  playerRef.current.playbackRate = .75
                                  break
                                case 2:
                                  playerRef.current.playbackRate = 1
                                  break
                                case 3:
                                  playerRef.current.playbackRate = 1.25
                                  break
                                case 4:
                                  playerRef.current.playbackRate = 1.5
                                  break
                              }
                            }
                          }}
                          sx={{
                            width: '100%',
                            height: '100%',
                          }}
                        >
                          {label}
                        </StepButton>
                      </Step>
                    ))}
                  </Stepper>
                  </Stack>
                </Paper>
							<PerformanceIcon
								sx={{
									transition: 'all 0.1s ease-in-out',
									cursor: 'pointer',
									fontSize: '3vw',
									color: '#fff',
									'&:hover': {
										transform: 'scale(1.4)',
									},
								}}
							/>
              </Stack>
								<FullscreenIcon
									onClick={() => handleFullscreen()}
									sx={{
										transition: 'all 0.1s ease-in-out',
										cursor: 'pointer',
										fontSize: '3vw',
										color: '#fff',
										'&:hover': {
											transform: 'scale(1.4)',
										},
									}}
								/>
							</Stack>
					</Stack>
				</BottomNavigation>
    	</Card>
		) : (
			<Card
				style={{
					position: 'absolute',
					backgroundColor: '#000',
					display: 'flex',
					flexDirection: 'column',
					alignItems: 'center',
					justifyContent: 'center',
					height: '100%',
					width: '100%',
				}}
			>
				<CircularProgress
						size="3vw"
						sx={{
							color: 'red',
							display: 'flex',
							alignItems: 'center',
							justifyContent: 'center',
							height: '100%',
							width: '100%',
						}}
					/>
			</Card>
		)}		
		</>
	);
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { id } = context.query;
	const res = await fetch(`http://localhost:3000/api/movies?imdb_id=${id}`);
	const media = await res.json();
  return {
    props: {
			media,
			id,
		},
  };
};