import Head from 'next/head';
import { useEffect, useState } from 'react';
import NavBar from '../../components/NavBar';
import Slider from '../../components/Slider';
import Banner from '../../components/Banner';
import Footer from '../../components/Footer';
import NavigateNextIcon from '@mui/icons-material/NavigateNext';
import { Grid, Skeleton, Stack, Paper, Typography } from '@mui/material';


export default function Movies() {
  const [movies, setMovies] = useState<Array<any>>([]);
  const [itemsToShow, setItemsToShow] = useState<any>([]);
  const [loaded, setLoaded] = useState(false);
  const items = [ 0, 1, 2, 3, 4, 5, 6 ];

  useEffect(() => {
    // Fetch api data
    fetch('/api/movies')
    .then(response => response.json())
    .then(data => {
      setMovies(data);
      setLoaded(true);
    });

    if (!loaded) {        
      for (let i = 0; i < items.length; i++) {
        setTimeout(() => {
          setItemsToShow((prevItems: any) => [...prevItems, items[i]]);
        }, i * 200);
      }
    } else {
      setItemsToShow([]);
    }
  }, []);

  // trending now
  const trendingNow = movies
  ?.filter((movie: any) => {
    const releaseDate = new Date(movie.release_date);
    const threeMonthsAgo = new Date();
    threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
    return releaseDate >= threeMonthsAgo;
  })
  .sort((a: any, b: any) => b.popularity - a.popularity)
  .slice(0, 24);

  // banner movie (first movie in trending now)
  const bannerMovie = trendingNow?.shift();

  // top rated
  const topRated = movies
  ?.sort((a: any, b: any) => b.vote_count - a.vote_count || b.score - a.score) // sort by vote count and score
  .filter((movie: any) => !trendingNow?.some((trend: any) => trend.id === movie.id) && movie.id !== bannerMovie?.id) // remove all trending movies
  .slice(0, 24);

  // popular
  const popular = movies
  ?.sort((a: any, b: any) => b.popularity - a.popularity)
  // remove all trending movies & top rated movies from popular and banner movie
  .filter((movie: any) => !trendingNow?.some((trend: any) =>
    trend.id === movie.id) && !topRated?.some((top: any) =>
    top.id === movie.id) && movie.id !== bannerMovie?.id)
  .slice(0, 24);

  return (
    <>
      <Head>
        <title>Movies - Nyetflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="main"
        style={{
          fontFamily: 'Netflix Sans,Helvetica Neue,Segoe UI,Roboto,Ubuntu,sans-serif',
          backgroundColor: '#141414',
          height: '100%',
          width: '100%',
          minWidth: '375px',
          minHeight: '700px',
      }}>
        <NavBar />
        { loaded ? (
          <>
            <Banner movie={bannerMovie} />
            <Stack spacing={0} sx={{ overflow: 'visible' }}>
              <Paper sx={{ 
                backgroundColor: 'transparent',
                marginTop: 'calc(-7vw - .5vw)',
                boxShadow: 'None',
                '&:hover': {
                  '& .MuiSvgIcon-root': {
                    opacity: '1',
                  },
                },
              }}>
                  <Typography variant="h4" 
                    className='explore'
                      sx={{
                        position: 'relative',
                        fontSize: '1.4vw',
                        lineHeight: '1.25vw',
                        verticalAlign: 'bottom',
                        letterSpacing: '.05em',
                        cursor: 'pointer',
                        fontWeight: 500,
                        fontFamily: 'inherit',
                        margin: '0 0 1vw 5%',
                        color: '#fff',
                        zIndex: 0,  
                        '&:hover': {
                        '& span': {
                          opacity: '1',
                          display: 'inline',
                          transition: 'opacity 5s ease-in-out',
                        },
                        '& svg': {
                          marginLeft: '5.7%',
                          transition: 'all .7s ease-in-out',
                        },
                      },
                    }}
                  >Trending Now
                    <Typography variant="h4" component="span" sx={{
                      display: 'none',
                      opacity: '0',
                      position: 'absolute',
                      fontSize: '.9vw',
                      lineHeight: '1.5vw',
                      verticalAlign: 'bottom',
                      letterSpacing: '.05em',
                      cursor: 'pointer',
                      fontWeight: 600,
                      fontFamily: 'inherit',
                      margin: '0 0 0 1%',
                      color: '#54b9c4',
                      zIndex: 0,
                    }}
                    >Explore All
                    </Typography>
                    <NavigateNextIcon sx={{ 
                      opacity: '0',
                      fontSize: '1.8vw',
                      position: 'absolute',
                      cursor: 'pointer',
                      bottom: '-.4vw',
                      margin: '0',
                      padding: '0',
                      color: '#54b9c4',
                    }} />
                  </Typography>
                  <Slider movies={trendingNow} />
              </Paper>
            </Stack>
            </>
        ) : (
          <div style={{
            display: 'flex',
            justifyContent: 'left',
            alignItems: 'left',
            height: '100vh',
            width: '150vw',
          }}
          >
            <Skeleton
              sx={{
                position: 'absolute',
                top: '8vw',
                left: '6vw',
                display: 'flex',
                justifyContent: 'left',
                alignItems: 'left',
                width: '10vw',
                height: '3vw',
                borderRadius: '0',
                backgroundColor: '#303030',
              }}
            />
            <Grid container
              sx={{
                display: 'flex',
                justifyContent: 'left',
                alignItems: 'left',
                margin: '11vw 0 0 6vw',
                width: '100%',
                height: '11vw',
                gap: '0.25vw',
              }}
            >
              {items.map((item) => (
                <Grid key={item} item sx={{
                  backgroundColor: `rgb(${(40 - item * 2)}, ${(40 - item * 2)}, ${(40 - item * 2)})`,
                  opacity: itemsToShow.includes(item) ? 1 : 0,
                  transition: `opacity 0.2s ease ${item * 0.1}s`,
                  width: '16vw',
                  height: '100%',
                  borderRadius: '5px',
                  }}
                />
              ))}
            </Grid>
          </div>
        )}
        <Footer />
      </main>
    </>
  )
}
