import Head from 'next/head';
import { useEffect, useState } from 'react';
import NavBar from '../../components/NavBar';
import MovieSlider from '../../components/Slider';
import Banner from '../../components/Banner';
import Footer from '../../components/Footer';
import { Grid, Skeleton } from '@mui/material';

export default function Home() {
  const [movies, setMovies] = useState<Array<any>>([]);
  const [itemsToShow, setItemsToShow] = useState<any>([]);
  const [loaded, setLoaded] = useState(false);
  const items = [ 0, 1, 2, 3, 4, 5, 6 ];

  useEffect(() => {
    // Fetch api data
    fetch('/api/movies')
    .then(response => response.json())
    .then(data => {
      setMovies(data);
      setLoaded(true);
    });

    if (!loaded) {        
      for (let i = 0; i < items.length; i++) {
        setTimeout(() => {
          setItemsToShow((prevItems: any) => [...prevItems, items[i]]);
        }, i * 200);
      }
    } else {
      setItemsToShow([]);
    }
  }, []);

  // trending now
  const trendingNow = movies
  ?.filter((movie: any) => {
    const releaseDate = new Date(movie.release_date);
    const threeMonthsAgo = new Date();
    threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
    return releaseDate >= threeMonthsAgo;
  })
  .sort((a: any, b: any) => b.popularity - a.popularity)
  .slice(0, 29);

  // banner movie (first movie in trending now)
  const bannerMovie = trendingNow?.shift();

  // top rated
  const topRated = movies
  ?.sort((a: any, b: any) => b.vote_count - a.vote_count || b.score - a.score) // sort by vote count and score
  .filter((movie: any) => !trendingNow?.some((trend: any) => trend.id === movie.id) && movie.id !== bannerMovie?.id) // remove all trending movies
  .slice(0, 28);

  // popular
  const popular = movies
  ?.sort((a: any, b: any) => b.popularity - a.popularity)
  // remove all trending movies & top rated movies from popular and banner movie
  .filter((movie: any) => !trendingNow?.some((trend: any) =>
    trend.id === movie.id) && !topRated?.some((top: any) =>
    top.id === movie.id) && movie.id !== bannerMovie?.id)
  .slice(0, 28);

  // action  
  const action = movies
    ?.filter((movie: any) => {
      const oneYearAgo = new Date();
      oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);
      // remove all trending movies & popular movies from top rated action
      if (
        trendingNow?.some((trend: any) => trend.id === movie.id) ||
        topRated?.some((top: any) => top.id === movie.id) ||
        popular?.some((pop: any) => pop.id === movie.id) ||
        bannerMovie?.id === movie.id
      ) {
        return false;
      }
      return movie.genre.includes('Action') && new Date(movie.release_date) >= oneYearAgo;
    })
    // sort by popularity
    .sort((a: any, b: any) => b.popularity - a.popularity)
    .slice(0, 28);
    
  // comedy
  const comedy = movies
    ?.filter((movie: any) => {
      const oneYearAgo = new Date();
      oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);
      if (
        trendingNow?.some((trend: any) => trend.id === movie.id) ||
        topRated?.some((top: any) => top.id === movie.id) ||
        popular?.some((pop: any) => pop.id === movie.id) ||
        action?.some((act: any) => act.id === movie.id) ||
        bannerMovie?.id === movie.id
      ) {
        return false;
      }
      return movie.genre.includes('Comedy') && new Date(movie.release_date) >= oneYearAgo;
    })
    .sort((a: any, b: any) => b.popularity - a.popularity)
    .slice(0, 28);

  // drama
  const drama = movies
    ?.filter((movie: any) => {
      const oneYearAgo = new Date();
      oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);
      // remove all trending movies & popular movies from top rated action
      if (
        trendingNow?.some((trend: any) => trend.id === movie.id) ||
        topRated?.some((top: any) => top.id === movie.id) ||
        popular?.some((pop: any) => pop.id === movie.id) ||
        action?.some((act: any) => act.id === movie.id) ||
        comedy?.some((com: any) => com.id === movie.id) ||
        bannerMovie?.id === movie.id
      ) {
        return false;
      }
      return movie.genre.includes('Drama') && new Date(movie.release_date) >= oneYearAgo;
    })
    .sort((a: any, b: any) => b.popularity - a.popularity)
    .slice(0, 28);

  return (
    <>
      <Head>
        <title>Movies - Nyetflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="main"
        style={{
          fontFamily: 'Netflix Sans,Helvetica Neue,Segoe UI,Roboto,Ubuntu,sans-serif',
          backgroundColor: '#141414',
          height: '100%',
          width: '100%',
          minWidth: '375px',
          minHeight: '700px',
      }}>
        <NavBar />
        { loaded ? (
          <>
        <Banner movie={bannerMovie} />
        <Grid container sx={{ flexGrow: 1, marginTop: 'calc(-9vw - .5vw)' }}>
        <Grid item sx={{ padding: '50px 0 20px 6%', zIndex: 1 }}>
              <h2 style={{
                fontSize: '1.4vw',
                lineHeight: '1.25vw',
                verticalAlign: 'bottom',
                fontWeight: 500,
              }}
              >Trending Now</h2>
          </Grid>
          <Grid item xs={12}>
            <MovieSlider movies={trendingNow} />
          </Grid>
          <Grid item sx={{ padding: '50px 0 20px 6%' }}>
              <h2 style={{
                  fontSize: '1.4vw',
                  lineHeight: '1.25vw',
                  verticalAlign: 'bottom',
                  fontWeight: 500,
                }}
              >Top Rated Movies</h2>
          </Grid>
          <Grid item xs={12}>
            <MovieSlider movies={topRated} />
          </Grid>
          <Grid item sx={{ padding: '50px 0 20px 6%' }}>
                <h2 style={{
                  fontSize: '1.4vw',
                  lineHeight: '1.25vw',
                  verticalAlign: 'bottom',
                  fontWeight: 500,
                }}
              >Popular on Nyetflix</h2>
          </Grid>
          <Grid item xs={12}>
            <MovieSlider movies={popular} />
          </Grid>
          <Grid item sx={{ padding: '50px 0 20px 6%' }}>
                <h2 style={{
                  fontSize: '1.4vw',
                  lineHeight: '1.25vw',
                  verticalAlign: 'bottom',
                  fontWeight: 500,
                }}
              >New Action Movies</h2>
          </Grid>
          <Grid item xs={12}>
            <MovieSlider movies={action} />
          </Grid>
          <Grid item sx={{ padding: '50px 0 20px 6%' }}>
                <h2 style={{
                  fontSize: '1.4vw',
                  lineHeight: '1.25vw',
                  verticalAlign: 'bottom',
                  fontWeight: 500,
                }}
              >New Comedy Movies</h2>
          </Grid>
          <Grid item xs={12}>
            <MovieSlider movies={comedy} />
          </Grid>
          <Grid item sx={{ padding: '50px 0 20px 6%' }}>
                <h2 style={{
                  fontSize: '1.4vw',
                  lineHeight: '1.25vw',
                  verticalAlign: 'bottom',
                  fontWeight: 500,
                }}
              >New Drama Movies</h2>
          </Grid>
          <Grid item xs={12}>
            <MovieSlider movies={drama} />
          </Grid>
        </Grid>
        </>
        ) : (
          <div style={{
            display: 'flex',
            justifyContent: 'left',
            alignItems: 'left',
            height: '100vh',
            width: '150vw',
          }}
          >
            <Skeleton
              sx={{
                position: 'absolute',
                top: '8vw',
                left: '6vw',
                display: 'flex',
                justifyContent: 'left',
                alignItems: 'left',
                width: '10vw',
                height: '3vw',
                borderRadius: '0',
                backgroundColor: '#303030',
              }}
            />
            <Grid container
              sx={{
                display: 'flex',
                justifyContent: 'left',
                alignItems: 'left',
                margin: '11vw 0 0 6vw',
                width: '100%',
                height: '11vw',
                gap: '0.25vw',
              }}
            >
              {items.map((item) => (
                <Grid key={item} item sx={{
                  backgroundColor: `rgb(${(40 - item * 2)}, ${(40 - item * 2)}, ${(40 - item * 2)})`,
                  opacity: itemsToShow.includes(item) ? 1 : 0,
                  transition: `opacity 0.2s ease ${item * 0.1}s`,
                  width: '16vw',
                  height: '100%',
                  borderRadius: '5px',
                  }}
                />
              ))}
            </Grid>
          </div>
        )}
        <Footer />
      </main>
    </>
  )
}
